{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service01.serviceAccountName" . }}
  labels:
{{ include "service01.labels" . | nindent 4 }}
{{- end -}}
