replicaCount: 1
image:
  registry: registry.cn-beijing.aliyuncs.com/microservicecicd/microservicecicd-service02-service
  pullPolicy: IfNotPresent
  version: 1.1.2-20210202220426
  commit: 3a0bcb896736fd9e99feed5bbc5ba4083ccca724
continers:
  port: 8081
  livenessProbe: /Hello
  readinessProbe: /Hello
service:
  type: ClusterIP
  port: 8081
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: service02.idevops.site
    paths:
    - /
  tls: []
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  name: null
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
